name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rmq_version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    env:
      RABBITMQ_VERSION: ${{ matrix.rmq_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: test
        run: make test

      - name: vet
        run: make vet

      - name: testacc
        run: make testacc
